services:
  - type: web
    name: amazon-scraper-api
    env: python
    plan: free
    buildCommand: pip install --only-binary=all -r requirements.txt && playwright install chromium
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
